openapi: 3.0.3
info:
  title: Personal Play challenge
  description: |-
    - Este es el desafío para aplicar al cargo "Developer" en TELECOM. El desafío consiste en aplicar habilidades en JavaScript Node.js y TypeScript.
  contact:
    email: aldocfabro@gmail.com
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: status
    description: endpoint to check backend status
paths:
  /:
    get:
      tags:
        - status
      summary: endpoint to check backend status
      description: Entry point to check server status
      operationId: statusServer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSuccess'
        '406':
          description: not acceptable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseError'
components:
  schemas:
    ApiResponseSuccess:
      type: object
      properties:
        error:
          type: boolean
          example: false
        status:
          type: integer
          format: int64
          example: 200
        message:
          type: string
          example: 'success'
        body:
          type: object
          properties:
            server:
              type: string
              example: 'ok'
    ApiResponseError:
      type: object
      properties:
        error:
          type: boolean
          example: true
        status:
          type: integer
          format: int64
          example: 406
        message:
          type: string
          example: 'error'
        body:
          type: object
          properties:
            server:
              type: string
              example: 'fail'
